spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.249.180:11416/tduck?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: tduckadmin
    password: tduckpassword
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
logging:
  level:
    com.tduck.cloud: debug
  config: classpath:logback-spring.xml

config:
  initPassword: 123456

rsa:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCMwSwaReHYXR/63yd18tTHhrEAb8qS5Pc3tsTZBBP10MWZ4eeH4il8xhC4+GpYXuXpLuxKlJlYN69JJoUybaaQoVyWX+sD2Kic3Eoz8ovLuHAg33E0jU53HZ+4p8uknHlhnlJs0drdnVoG/CjpD90tEDnu2aPoFP4LtPgbawuOrwIDAQAB
  privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAIzBLBpF4dhdH/rfJ3Xy1MeGsQBvypLk9ze2xNkEE/XQxZnh54fiKXzGELj4alhe5eku7EqUmVg3r0kmhTJtppChXJZf6wPYqJzcSjPyi8u4cCDfcTSNTncdn7iny6SceWGeUmzR2t2dWgb8KOkP3S0QOe7Zo+gU/gu0+BtrC46vAgMBAAECgYEAgrC+NWrbh1z4W6Sl7CNbpCOQ55nlGr2UOdvvLJ1Xty9wujACHa5F3T++uTCW9ZSvnvLdnWYad8nEbIRium8LbudT8MWSp431Awv+dg8LMenj1xuhybIOPvxMuaR76WPl5jQsOyoN5BYWXHlSxiky4DLYIAl+CaJi34vd2WNbMjECQQDuj2jwtOmQhGBfDzD625QlABZUO0rKV9eh2xwvQEqh3s2LGlGJ3/vBvaLVyxWW2hvLVwljR0ubHpTojxODdPvHAkEAlwtbQlM5FCLvsdMCm5muLeLP8l3aXVf1yahXJruUvjlJdrNAm9EbLrffh6GZSBjZgJc1cGEMkMYO657Nu87F2QJBAK6olJ5W9gH2yVAPoT6o8Oe+DpsQ5gsLETbRYus9WOb2ZuqHFFerg3kvTD7W9zGA8oSHbrofAr3JQCCcUB8Y0RUCQFSPZQ3irafaTzrMmT8ncF38BtL3PBLZ9Z5qAjCK/6DnTXuIqvkQvhkPk7LJA5lbYBkfjilWC8TZPO0oQKGOBzECQQCIG/YviBWhCJJgOPaHdge6SV/d0vm4E1jFCnCH7FDd0TR0kF/pDSoFoRdoXZdCLCEozlQ2C9fcgN4YqZ9OwDq3
