spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tduck?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mail:
    #host: smtp.exmail.qq.com
    host: smtp.qq.com
    username: 1489878447@qq.com
    password: njlaxouyaoikhddi

logback:
  logpath: D:/ruoyi/tduck/logs

logging:
  level:
    com.tduck.cloud: debug
  config: classpath:logback-spring.xml

platform:
  #oss:
  #ossType: 1
  #endpoint: 12
  #accessKeyId: mpw:vT2DiLH0raFqd2+10sAGbvhyYQsWKuxj2YOnXAh+ZhAsMkhqcQBSa5tQosuposvs
  #accessKeySecret: mpw:ZRJuLL9+aiBq+9PUN3wjrglLNvuK2yhKhrnSzw5P36P/E9QP4EIOIObeQvYjpaV/
  #bucketName: tduck-cloud
  #domain: https://qiniu.smileyi.top
  oss:
    ossType: 3 # 3表示使用本地存储
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
    domain: ${platform.front.baseUrl}tduck-api/profile  #对外访问的地址 使用后端项目部署的ip+端口 后面可以固定
    upload-folder: D:\ruoyi\uploadPath\tduck #文件存放的位置
    access-path-pattern: /profile/**  # 文件访问路径前缀 这里更改domain也需要更改
  sms:
    type: 1  # 短信平台类型
    secretId: mpw:EvC1LR0eGdzeQzkuO7fhEazxGtmdue8FJDzSA1l+gICuOUEDXI8zcjK+VXB2aWKS
    secretKey: mpw:W3kvWxvHdgUJPAwqR6mwpfMoQMerAYcxZGHwJc259lK3m+jzceGuu0Tgnx++02Bk
    appId: 1400461467
    sign: 投票/问卷
    validateCodeTemplateId: 808150
    retrievePwdValidateCodeTemplateId: 809014
  front:
    baseUrl: http://192.168.0.9:8888/
    resetPwdUrl: ${platform.front.baseUrl}forget/password?code={}&email={}
    updateEmailUrl: ${platform.front.baseUrl}account/validate?type=updateEmail&code={}&email={}
wx:
  mp:
    redis-config-key-prefix: wx
    configs:
      - appId: wx0f7d934c69e78d06
        secret: 65a8d102b1ed868015981a7a0a6c050f
        token: 4RxTRQGra0TACzttk+84TRsnVhTyG6a/peX0v+KZgyg=
        aesKey:
